# Generated by Django 5.1.5 on 2025-02-08 23:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_the_loai', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['ten_the_loai'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, help_text='Phản hồi của người dùng về dịch vụ', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hien_thi', models.CharField(max_length=255)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='uploads/avatars/')),
                ('gioi_tinh', models.SmallIntegerField(choices=[(0, 'Nam'), (1, 'Nữ'), (2, 'Khác')], default=0, help_text='Giới tính của người dùng')),
                ('role', models.IntegerField(choices=[(0, 'Người dùng'), (1, 'Tác giả'), (2, 'Quản trị viên')], default=0, help_text='Vai trò của người dùng')),
                ('last_role', models.IntegerField(choices=[(0, 'Người dùng'), (1, 'Tác giả'), (2, 'Quản trị viên')], default=0, help_text='Vai trò trước đây của người dùng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thong_tin_nguoi_dung', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tac_gia', models.CharField(max_length=255)),
                ('is_locked', models.BooleanField(default=False, help_text='Tác giả bị khóa hay không')),
                ('id_nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tac_gia', to='book.thongtinnguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_truyen', models.CharField(max_length=255, unique=True)),
                ('so_luong_chuong', models.PositiveIntegerField(default=0)),
                ('tom_tat_noi_dung', models.TextField(help_text='Tóm tắt nội dung chính của truyện. Không giới hạn độ dài.')),
                ('anh_dai_dien', models.ImageField(upload_to='uploads/truyen/')),
                ('luot_xem', models.PositiveIntegerField(default=0)),
                ('luot_thich', models.PositiveIntegerField(default=0)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('trang_thai', models.CharField(choices=[('dang_ra', 'Đang ra'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngừng')], default='dang_ra', max_length=20)),
                ('khoa', models.BooleanField(default=False)),
                ('id_tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen', to='book.tacgia')),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinChuongTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuong', models.CharField(max_length=255)),
                ('noi_dung_chuong', models.TextField()),
                ('thu_tu', models.IntegerField(default=0)),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuong_truyen', to='book.truyen')),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='TruyenYeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_yeu_thich_user', to='book.thongtinnguoidung')),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_yeu_thich_list', to='book.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='Chuongdadoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian_doc', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='da_doc_chuong', to=settings.AUTH_USER_MODEL)),
                ('chuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luot_doc', to='book.thongtinchuongtruyen')),
            ],
            options={
                'ordering': ['-thoigian_doc'],
                'constraints': [models.UniqueConstraint(fields=('user', 'chuong'), name='unique_user_chuong_dadoc')],
            },
        ),
        migrations.CreateModel(
            name='ThichTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian_thich', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_da_thich', to=settings.AUTH_USER_MODEL)),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_luot_thich', to='book.truyen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'id_truyen'), name='unique_user_thich_truyen')],
            },
        ),
        migrations.CreateModel(
            name='TheLoaiTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('id_the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_thuoc_the_loai', to='book.theloai')),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_loai_cua_truyen', to='book.truyen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_truyen', 'id_the_loai'), name='unique_truyen_theloai')],
            },
        ),
        migrations.CreateModel(
            name='Luotxem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('thoigian_xem', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luot_xem_user', to=settings.AUTH_USER_MODEL)),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_luot_xem', to='book.truyen')),
            ],
            options={
                'indexes': [models.Index(fields=['id_truyen', 'ip_address', 'thoigian_xem'], name='book_luotxe_id_truy_71d43c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DanhgiaTruyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danhgia', models.IntegerField(help_text='Đánh giá từ 0 đến 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('binhluan', models.TextField(blank=True, help_text='Bình luận về truyện (Tùy chọn)', null=True)),
                ('thoigian_danhgia', models.DateTimeField(auto_now_add=True)),
                ('capnhat', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_truyen', to=settings.AUTH_USER_MODEL)),
                ('id_truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='book.truyen')),
            ],
            options={
                'ordering': ['-thoigian_danhgia'],
                'constraints': [models.UniqueConstraint(fields=('user', 'id_truyen'), name='unique_user_danhgia_truyen')],
            },
        ),
    ]
