# Generated by Django 5.1.5 on 2025-05-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_danhgiatruyen_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhgiatruyen',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='danhgiatruyen',
            name='unique_user_danhgia_truyen',
        ),
    ]
